MAJOR updated pipeline file to add auto merge_22

diff --git a/.github/workflows/tag.yml b/.github/workflows/tag.yml
--- a/.github/workflows/tag.yml
+++ b/.github/workflows/tag.yml
@@ -27,7 +27,169 @@ permissions:
   pull-requests: write
 
 jobs:
+
+  create_tag_for_deployment:
+    
+    runs-on: ubuntu-latest
+    outputs:
+      NEW_TAG: ${{ steps.get_version.outputs.NEW_TAG }}
+      COMMIT_MESSAGE: ${{ steps.pr_commit_message.outputs.COMMIT_MESSAGE }}
+    permissions:
+      id-token: write # This is required for requesting the JWT
+      contents: write  # Allow GITHUB_TOKEN to write to repository contents
+      pull-requests: write  # Allow GITHUB_TOKEN to create and manage pull requests
+    steps:
+      - name: Checkout code from PR branch
+        uses: actions/checkout@v3
+        with:
+          ref: ${{ github.head_ref }} 
+          # token: ${{ secrets.GITHUB_TOKEN }}
+          
+      - name: Set up Git for tagging
+        run: |
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git config --global user.name "github-actions[bot]"
+      - name: Fetch tags from remote
+        run: |
+          git fetch --tags
+      - name: Get latest tag and determine version increment
+        id: get_version
+        run: |
+          # Get the latest tag in the repo
+          LATEST_TAG=$(git tag --list 'tag-v*' | sort -V | tail -n 1)
+          if [ -z "$LATEST_TAG" ]; then
+            LATEST_TAG="tag-v0.0.0"
+          fi
+          # Parse version components (e.g., tag-v1.0.0 -> MAJOR=1, MINOR=0, PATCH=0)
+          VERSION="${LATEST_TAG//tag-v/}"
+          VERSION_PARTS=(${VERSION//./ })
+          MAJOR="${VERSION_PARTS[0]}"
+          MINOR="${VERSION_PARTS[1]}"
+          PATCH="${VERSION_PARTS[2]}"
+          # Check commit message for version increment and modify
+          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
+          
+          if [[ "$COMMIT_MESSAGE" == *MAJOR* ]]; then
+            MAJOR=$((MAJOR + 1))
+            MINOR=0
+            PATCH=0
+          elif [[ "$COMMIT_MESSAGE" == *MINOR* ]]; then
+            MINOR=$((MINOR + 1))
+            PATCH=0
+          elif [[ "$COMMIT_MESSAGE" == *PATCH* ]]; then
+            PATCH=$((PATCH + 1))
+          fi
+          # Set new tag
+          NEW_TAG="tag-v${MAJOR}.${MINOR}.${PATCH}"
+          # Ensure the tag is unique (increment PATCH if necessary)
+          while git rev-parse "$NEW_TAG" >/dev/null 2>&1; do
+            PATCH=$((PATCH + 1))
+            NEW_TAG="tag-v${MAJOR}.${MINOR}.${PATCH}"
+          done
+          echo "New tag: $NEW_TAG"
+          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
+          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
+          # echo "::set-output name=NEW_TAG::$NEW_TAG"
+
+      - name: Create and push tag from feature branch
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          NEW_TAG="${{ env.NEW_TAG }}"
+          git tag $NEW_TAG
+          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
+          git push origin $NEW_TAG
+          echo "Created and pushed tag: $NEW_TAG"
+
+      - name: Fetch PR commit message using GitHub API
+        id: pr_commit_message
+        run: |
+          PR_NUMBER="${{ github.event.pull_request.number }}"
+          COMMIT_MESSAGE=$(curl -s \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" \
+            | jq -r '.title + " " + .body')
+          # Remove newlines and extra spaces
+          COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE" | tr -d '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
+          # Set commit message for later use
+          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
+          echo "Fetched Commit Message: $COMMIT_MESSAGE"
+          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
+
+      - name: Fetch PR changed files using GitHub API
+        id: changed_files
+        run: |
+          # Ensure PR number is available
+          PER_PAGE=100
+          PR_NUMBER="${{ github.event.pull_request.number }}"
+          echo "PR Number: $PR_NUMBER"
+          if [ -z "$PR_NUMBER" ]; then
+            echo "PR number not found. Exiting."
+            exit 1
+          fi
+          echo "Fetching changed files for PR #$PR_NUMBER..."
+
+          # Fetch the changed files from the PR using GitHub API
+          RESPONSE=$(curl -s \
+            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/files?per_page=$PER_PAGE")
+
+          # Check if the response is empty or malformed
+          if [ -z "$RESPONSE" ]; then
+            echo "API response is empty. Exiting."
+            exit 1
+          fi
+
+          # Extract filenames and status using jq
+          CHANGED_FILES=$(echo "$RESPONSE" | jq -r '.[] | select(.status != "removed") | .filename')
+
+
+          # Check if files are being returned
+          if [ -z "$CHANGED_FILES" ]; then
+            echo "No files found in the PR. Exiting."
+            exit 1
+          fi
+
+          # Filter only files in the /src path (ignoring files outside /infra/src/dags/)
+          SRC_CHANGED_FILES=$(echo "$CHANGED_FILES" | grep -E "^infra/src/dags/" || echo "")
+
+          # Display the count of changed files
+          CHANGED_FILES_COUNT=$(echo "$CHANGED_FILES" | wc -l)
+          echo "all changed files count: $CHANGED_FILES_COUNT"
+          SRC_CHANGED_FILES_COUNT=$(echo "$SRC_CHANGED_FILES" | wc -l)
+          echo "SRC changed files count: $SRC_CHANGED_FILES_COUNT"
+
+          # Handle the case where no files match the filter
+          if [ -z "$SRC_CHANGED_FILES" ]; then
+            echo "No files changed in path 'infra/src/dags/'."
+            echo "Skipping further steps."
+            # You can exit successfully if no relevant files are found
+            exit 0
+          else
+            echo "Files changed in 'infra/src/dags/':"
+            echo "$SRC_CHANGED_FILES"
+            echo "Current working directory: $(pwd)"
+            echo "$SRC_CHANGED_FILES" > dags_changed_files.txt
+            echo "$CHANGED_FILES" > all_changed_files.txt
+          fi
+          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
+
+      - name: Upload all_changed_files.txt artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: all-changed-files
+          path: all_changed_files.txt
+
+      - name: Upload dags_changed_files.txt artifact
+        uses: actions/upload-artifact@v3
+        with:
+          name: dags-changed-files
+          path: dags_changed_files.txt
+
+##########################################################################          
   check-approval:
+    name: Validating_PR_Approval
+    needs: create_tag_for_deployment
     runs-on: ubuntu-latest
     outputs:
       approval-status: ${{ steps.check-approval.outputs.status }}
@@ -198,163 +360,7 @@ jobs:
           gh pr merge $pr_number --merge
           echo "PR #$pr_number merged successfully into main."
 ##############################################################################################################
-  create_tag_for_deployment:
-    needs: validate_created_pr
-    runs-on: ubuntu-latest
-    outputs:
-      NEW_TAG: ${{ steps.get_version.outputs.NEW_TAG }}
-      COMMIT_MESSAGE: ${{ steps.pr_commit_message.outputs.COMMIT_MESSAGE }}
-    permissions:
-      id-token: write # This is required for requesting the JWT
-      contents: write  # Allow GITHUB_TOKEN to write to repository contents
-      pull-requests: write  # Allow GITHUB_TOKEN to create and manage pull requests
-    steps:
-      - name: Checkout code from PR branch
-        uses: actions/checkout@v3
-        with:
-          ref: ${{ github.head_ref }} 
-          # token: ${{ secrets.GITHUB_TOKEN }}
-          
-      - name: Set up Git for tagging
-        run: |
-          git config --global user.email "github-actions[bot]@users.noreply.github.com"
-          git config --global user.name "github-actions[bot]"
-      - name: Fetch tags from remote
-        run: |
-          git fetch --tags
-      - name: Get latest tag and determine version increment
-        id: get_version
-        run: |
-          # Get the latest tag in the repo
-          LATEST_TAG=$(git tag --list 'tag-v*' | sort -V | tail -n 1)
-          if [ -z "$LATEST_TAG" ]; then
-            LATEST_TAG="tag-v0.0.0"
-          fi
-          # Parse version components (e.g., tag-v1.0.0 -> MAJOR=1, MINOR=0, PATCH=0)
-          VERSION="${LATEST_TAG//tag-v/}"
-          VERSION_PARTS=(${VERSION//./ })
-          MAJOR="${VERSION_PARTS[0]}"
-          MINOR="${VERSION_PARTS[1]}"
-          PATCH="${VERSION_PARTS[2]}"
-          # Check commit message for version increment and modify
-          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
-          
-          if [[ "$COMMIT_MESSAGE" == *MAJOR* ]]; then
-            MAJOR=$((MAJOR + 1))
-            MINOR=0
-            PATCH=0
-          elif [[ "$COMMIT_MESSAGE" == *MINOR* ]]; then
-            MINOR=$((MINOR + 1))
-            PATCH=0
-          elif [[ "$COMMIT_MESSAGE" == *PATCH* ]]; then
-            PATCH=$((PATCH + 1))
-          fi
-          # Set new tag
-          NEW_TAG="tag-v${MAJOR}.${MINOR}.${PATCH}"
-          # Ensure the tag is unique (increment PATCH if necessary)
-          while git rev-parse "$NEW_TAG" >/dev/null 2>&1; do
-            PATCH=$((PATCH + 1))
-            NEW_TAG="tag-v${MAJOR}.${MINOR}.${PATCH}"
-          done
-          echo "New tag: $NEW_TAG"
-          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
-          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT
-          # echo "::set-output name=NEW_TAG::$NEW_TAG"
-
-      - name: Create and push tag from feature branch
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          NEW_TAG="${{ env.NEW_TAG }}"
-          git tag $NEW_TAG
-          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
-          git push origin $NEW_TAG
-          echo "Created and pushed tag: $NEW_TAG"
-
-      - name: Fetch PR commit message using GitHub API
-        id: pr_commit_message
-        run: |
-          PR_NUMBER="${{ github.event.pull_request.number }}"
-          COMMIT_MESSAGE=$(curl -s \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}" \
-            | jq -r '.title + " " + .body')
-          # Remove newlines and extra spaces
-          COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE" | tr -d '\n' | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
-          # Set commit message for later use
-          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
-          echo "Fetched Commit Message: $COMMIT_MESSAGE"
-          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
-
-      - name: Fetch PR changed files using GitHub API
-        id: changed_files
-        run: |
-          # Ensure PR number is available
-          PER_PAGE=100
-          PR_NUMBER="${{ github.event.pull_request.number }}"
-          echo "PR Number: $PR_NUMBER"
-          if [ -z "$PR_NUMBER" ]; then
-            echo "PR number not found. Exiting."
-            exit 1
-          fi
-          echo "Fetching changed files for PR #$PR_NUMBER..."
-
-          # Fetch the changed files from the PR using GitHub API
-          RESPONSE=$(curl -s \
-            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/files?per_page=$PER_PAGE")
-
-          # Check if the response is empty or malformed
-          if [ -z "$RESPONSE" ]; then
-            echo "API response is empty. Exiting."
-            exit 1
-          fi
-
-          # Extract filenames and status using jq
-          CHANGED_FILES=$(echo "$RESPONSE" | jq -r '.[] | select(.status != "removed") | .filename')
-
-
-          # Check if files are being returned
-          if [ -z "$CHANGED_FILES" ]; then
-            echo "No files found in the PR. Exiting."
-            exit 1
-          fi
-
-          # Filter only files in the /src path (ignoring files outside /infra/src/dags/)
-          SRC_CHANGED_FILES=$(echo "$CHANGED_FILES" | grep -E "^infra/src/dags/" || echo "")
-
-          # Display the count of changed files
-          CHANGED_FILES_COUNT=$(echo "$CHANGED_FILES" | wc -l)
-          echo "all changed files count: $CHANGED_FILES_COUNT"
-          SRC_CHANGED_FILES_COUNT=$(echo "$SRC_CHANGED_FILES" | wc -l)
-          echo "SRC changed files count: $SRC_CHANGED_FILES_COUNT"
-
-          # Handle the case where no files match the filter
-          if [ -z "$SRC_CHANGED_FILES" ]; then
-            echo "No files changed in path 'infra/src/dags/'."
-            echo "Skipping further steps."
-            # You can exit successfully if no relevant files are found
-            exit 0
-          else
-            echo "Files changed in 'infra/src/dags/':"
-            echo "$SRC_CHANGED_FILES"
-            echo "Current working directory: $(pwd)"
-            echo "$SRC_CHANGED_FILES" > dags_changed_files.txt
-            echo "$CHANGED_FILES" > all_changed_files.txt
-          fi
-          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
-
-      - name: Upload all_changed_files.txt artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: all-changed-files
-          path: all_changed_files.txt
-
-      - name: Upload dags_changed_files.txt artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: dags-changed-files
-          path: dags_changed_files.txt
+  
           
 ##############################################################################################################
   dev_changelog_pr_approve_it_manually:
@@ -453,7 +459,7 @@ jobs:
       - name: Authenticate GitHub CLI
         run: |
           echo "${{ secrets.PR_TOKEN }}" | gh auth login --with-token
-          
+
       - name: Merge the PR
         run: |
           echo "Merging the PR..."
