MAJOR added PR validation

diff --git a/.github/workflows/tag.yml b/.github/workflows/tag.yml
--- a/.github/workflows/tag.yml
+++ b/.github/workflows/tag.yml
@@ -18,6 +18,14 @@ jobs:
       github.event.pull_request.state == 'open'
     runs-on: ubuntu-latest
     steps:
+      - name: Check if PR template is filled out
+        run: |
+          PR_DESCRIPTION="${{ github.event.pull_request.body }}"
+          
+          if [[ -z "$PR_DESCRIPTION" || "$PR_DESCRIPTION" =~ "### Description of changes" || "$PR_DESCRIPTION" =~ "### Files Changed" || "$PR_DESCRIPTION" =~ "### Reason for Change" || "$PR_DESCRIPTION" =~ "### Task/Ticket/Issue" ]]; then
+            echo "PR Description is missing required fields (e.g. description, files changed, task). Please update the PR description."
+            exit 1
+          fi
       - name: Checkout code from PR branch
         uses: actions/checkout@v3
         with:
@@ -130,7 +138,7 @@ jobs:
           cat CHANGELOG_Dev.md
 
           # Add a changelog entry for the Dev deployment with PR commit message
-          echo -e "\n## [${TAG_NAME}] - $DATE\n### Deployed to:\n- **${ENVIRONMENT}**: ${DATE}\n### Changes:\n- Deploying version ${TAG_NAME}\n- Commit Message: $COMMIT_MESSAGE\n" >> CHANGELOG_Dev.md
+          echo -e "\n## [${TAG_NAME}] - $DATE\n### Deployed to:\n- **${ENVIRONMENT}**: ${DATE}\n### Changes:\n- Deployed version ${TAG_NAME}\n- Commit Message: $COMMIT_MESSAGE\n" >> CHANGELOG_Dev.md
 
           # View the content of the changelog after appending
           echo "Content of CHANGELOG_Dev.md after appending:"
@@ -186,7 +194,7 @@ jobs:
           git pull origin main
 
           # Add a changelog entry for the Qa deployment with PR commit message
-          echo -e "\n## [${TAG_NAME}] - $DATE\n### Deployed to:\n- **${ENVIRONMENT}**: ${DATE}\n### Changes:\n- Deploying version ${TAG_NAME}\n- Commit Message: $COMMIT_MESSAGE\n" >> CHANGELOG_Qa.md
+          echo -e "\n## [${TAG_NAME}] - $DATE\n### Deployed to:\n- **${ENVIRONMENT}**: ${DATE}\n### Changes:\n- Deployed version ${TAG_NAME}\n- Commit Message: $COMMIT_MESSAGE\n" >> CHANGELOG_Qa.md
 
           # Commit and push changes
           git add CHANGELOG_Qa.md
@@ -234,7 +242,7 @@ jobs:
           git pull origin main
 
           # Add a changelog entry for the Prod deployment with PR commit message
-          echo -e "\n## [${TAG_NAME}] - $DATE\n### Deployed to:\n- **${ENVIRONMENT}**: ${DATE}\n### Changes:\n- Deploying version ${TAG_NAME}\n- Commit Message: $COMMIT_MESSAGE\n" >> CHANGELOG_Prod.md
+          echo -e "\n## [${TAG_NAME}] - $DATE\n### Deployed to:\n- **${ENVIRONMENT}**: ${DATE}\n### Changes:\n- Deployed version ${TAG_NAME}\n- Commit Message: $COMMIT_MESSAGE\n" >> CHANGELOG_Prod.md
 
           # Commit and push changes
           git add CHANGELOG_Prod.md
